In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.6.0


#### Creating Tensors with tf.constant()<br>
constant tensors are immutable

In [5]:
scalar = tf.constant(7)

In [6]:
# checking dimension
scalar.ndim

0

In [8]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [9]:
vector.ndim

1

In [10]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [11]:
matrix.ndim

2

In [12]:
# creating matrix and defining data type using dtype
matrix = tf.constant([[1,2,3],
                     [4,5,6]], dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

In [13]:
matrix.ndim

2

In [14]:
# (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [15]:
tensor.ndim

3

#### Creating Tensors with tf.Variable()<br>

he difference between tf.Variable() and tf.constant() is tensors created with tf.constant() are immutable 

In [17]:
change_tensor = tf.Variable([10, 7])
unchange_tensor = tf.constant([10, 7])
change_tensor, unchange_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [24]:
# change_tensor[0] = 7 # error
change_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

We can here see that the value in change_tensor changed numpy=array([7, 7]

#### We can create random tensors by using the tf.random.Generator class.

In [26]:
# Here from_seed(42) values are same so the two random values will be same
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [27]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [31]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

In [29]:
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.2730574 , -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.2829171 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle a tensor (valuable for when you want to shuffle your data)

In [32]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

In [46]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

!!! IMP Here we can see the seed value is 42 but in every code run it changes so, to prevent this we need to use global seed

In [53]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42) # Here local seed is not necessary

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [54]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

### Other ways to make tensors

In [57]:
tf.ones((3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [58]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [59]:
tf.zeros((3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [60]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

# You can also turn NumPy arrays in into tensors.<br>

Remember, the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

In [67]:
import numpy as np
arr = np.arange(1, 25, dtype=np.int32)
arr.dtype

dtype('int32')

In [68]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [72]:
tensor = tf.constant(arr, shape=[2, 4, 3])
tensor

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

# reshape tensor

In [75]:
tf.reshape(tensor, (6, 4))

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

# Getting information from tensors (shape, rank, size)<br>
<b>Shape:</b> The length (number of elements) of each of the dimensions of a tensor.<br>
<b>Rank:</b> The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n<br>
<b>Axis or Dimension:</b> A particular dimension of a tensor.<br>
<b>Size:</b> The total number of items in the tensor.<br>

In [76]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [77]:
rank_4_tensor.shape

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [78]:
rank_4_tensor.ndim

4

In [82]:
tf.size(rank_4_tensor).numpy() 

120

In [83]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [84]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [85]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [86]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [95]:
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [96]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [97]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

#### You can also add dimensions to your tensor whilst keeping the same information present using tf.newaxis

In [99]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [100]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

#### You can achieve the same using tf.expand_dims()

In [101]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

# Manipulating tensors (tensor operations)

## Basic operations

In [103]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [104]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [105]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [106]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [107]:
tensor // 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 0]])>

In [108]:
tensor ** 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1410065408,  282475249],
       [     59049,    1048576]])>

##### Using tensorflow functions

In [109]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [110]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [115]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

# Matrix mutliplication

1) The inner dimensions must match:

(3, 5) @ (3, 5) won't work<br>
(5, 3) @ (3, 5) will work<br>
(3, 5) @ (5, 3) will work<br>

2) The resulting matrix has the shape of the outer dimensions:

(5, 3) @ (3, 5) -> (5, 5)<br>
(3, 5) @ (5, 3) -> (3, 3)

In [119]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [120]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [121]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [122]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

In [123]:
# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [ ]:
X @ Y # error so need to change the shape

In [127]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [130]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

# Transpose of a matrix 

In [132]:
# Try matrix multiplication 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

(3, 2) @ (2, 3) -> (3, 3) The output is based on outer layer this eg (3, 3)<br>
(2, 3) @ (3, 2) -> (2, 2) Here (2, 2)

# The dot product<br>
Multiplying matrices by each other is also referred to as the dot product.<br>
 perform the tf.matmul() operation using tf.tensordot().

In [133]:
# Perform the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

You might notice that although using both reshape and tranpose work, you get different results when using each.
<br>
Let's see an example, first with tf.transpose() then with tf.reshape().

In [134]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [135]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear
<br>
tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.

# Changing the datatype of a tensor. tf.cast()

In [141]:
t = tf.constant([10, 5], dtype=tf.float16)
t

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.,  5.], dtype=float16)>

In [142]:
T = tf.cast(t, dtype=tf.int16)
T

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([10,  5], dtype=int16)>

# Getting the absolute value- cvt -ve to +ve<br>
Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.<br>
To do so, you can use tf.abs().

In [148]:
# Create tensor with negative values
D = tf.constant([-7, -10, -1 ,-3 , -2])
D

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ -7, -10,  -1,  -3,  -2])>

In [149]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 7, 10,  1,  3,  2])>

# Finding the min, max, mean, sum (aggregation)

tf.reduce_min() - find the minimum value in a tensor.<br>
tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability)<br>
tf.reduce_mean() - find the mean of all elements in a tensor.<br>
tf.reduce_sum() - find the sum of all elements in a tensor.<br>
tf.math_reduce_std() - find the standard deviation<br>
tf.math_reduce_variance() - find the variance

In [227]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([75, 72, 99, 30, 99, 65, 60, 23, 57, 33, 58, 49, 96, 33, 25,  0, 99,
       22, 45, 35, 79, 14, 33, 79, 89, 40, 80, 83, 13, 77, 35, 90, 67, 81,
       82, 80, 68, 37, 44, 58, 40, 97, 88, 80, 68, 40, 15, 79, 93, 59])>

In [157]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [158]:
# Find the max
tf.reduce_max(E).numpy()

92

In [159]:
# Find the mean
tf.reduce_mean(E).numpy()

47

In [160]:
# Find the median
tf.reduce_sum(E).numpy()

2373

In [235]:
# Find the variance 
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.864704>

In [236]:
# Find the variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=721.7124>

# OR we can use tfp.status.variance 

# Finding the positional maximum and minimum<br>
tf.argmax() - find the position of the maximum element in a given tensor.<br>
tf.argmin() - find the position of the minimum element in a given tensor.

In [167]:
# Create a tensor with 50 values between 0 and 1
arr = tf.constant(np.random.random(50))
arr

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.00476815, 0.80716122, 0.62681883, 0.4051423 , 0.2481714 ,
       0.13797923, 0.96582189, 0.28949156, 0.23120972, 0.22413415,
       0.99087148, 0.3288165 , 0.93856822, 0.17468454, 0.93717196,
       0.0444067 , 0.06165273, 0.23836195, 0.82483873, 0.88441968,
       0.30212886, 0.56959206, 0.46979503, 0.48108279, 0.62908702,
       0.0043571 , 0.15970031, 0.47791845, 0.96314243, 0.35234031,
       0.63752207, 0.84637871, 0.24869719, 0.1184176 , 0.6593606 ,
       0.87909535, 0.83411555, 0.70150855, 0.51946079, 0.99169337,
       0.31946942, 0.95303412, 0.49573257, 0.17125984, 0.48378174,
       0.03969493, 0.21750602, 0.51555752, 0.97004913, 0.77056456])>

In [168]:
# Find the maximum element position of arr
tf.argmax(arr)

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [171]:
# Find the minimum element position of arr
tf.argmin(arr).numpy()

25

In [172]:
# Find the maximum element position of arr
print(f"The maximum value of arr is at position: {tf.argmax(arr).numpy()}") 
print(f"The maximum value of arr is: {tf.reduce_max(arr).numpy()}") 
print(f"Using tf.argmax() to index arr, the maximum value of arr is: {arr[tf.argmax(arr)].numpy()}")
print(f"Are the two max values the same (they should be)? {arr[tf.argmax(arr)].numpy() == tf.reduce_max(arr).numpy()}")

The maximum value of arr is at position: 39
The maximum value of arr is: 0.9916933667540858
Using tf.argmax() to index arr, the maximum value of arr is: 0.9916933667540858
Are the two max values the same (they should be)? True


# Squeezing a tensor (removing all single dimensions)<br>
to remove single-dimensions from a tensor (dimensions with size 1), can use tf.squeeze().

In [176]:
# rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
t = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
t

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int32, numpy=
array([[[[[42, 83, 36, 58, 43, 67, 66, 20, 22, 46,  1, 53, 56, 10, 12,
            8, 29,  6,  3, 71, 51, 92, 21, 22, 10, 82, 45, 69, 40, 78,
           53, 34, 18, 45, 28, 32, 92, 62, 32, 24, 88, 43, 82,  4, 13,
           10, 26, 31, 53, 11]]]]])>

In [177]:
t.shape, t.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [180]:
# Squeeze tensor t (remove all 1 dimensions)
t_squeeze = tf.squeeze(t)
t_squeeze

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([42, 83, 36, 58, 43, 67, 66, 20, 22, 46,  1, 53, 56, 10, 12,  8, 29,
        6,  3, 71, 51, 92, 21, 22, 10, 82, 45, 69, 40, 78, 53, 34, 18, 45,
       28, 32, 92, 62, 32, 24, 88, 43, 82,  4, 13, 10, 26, 31, 53, 11])>

In [181]:
t_squeeze.shape, t_squeeze.ndim

(TensorShape([50]), 1)

# One-hot encoding<br>

In [187]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode 
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [188]:
# One hot encode
tf.one_hot(some_list, depth=6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]], dtype=float32)>

#### We can specify on value and off value default it is 0 and 1

In [190]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="hello", off_value="tensor")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hello', b'tensor', b'tensor', b'tensor'],
       [b'tensor', b'hello', b'tensor', b'tensor'],
       [b'tensor', b'tensor', b'hello', b'tensor'],
       [b'tensor', b'tensor', b'tensor', b'hello']], dtype=object)>

# Squaring, log, square root

In [197]:
# Create a new tensor
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [192]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
# Find the squareroot (will error), needs to be non-integer so we need to convert into to float 
tf.sqrt(H)

In [199]:
H = tf.cast(H, dtype=tf.float16)
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [200]:
# Find the log (input also needs to be float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

# Manipulating tf.Variable tensors<br>
Tensors created with tf.Variable() can be changed in place using methods such as:<br>
1) assign() - assign a different value to a particular index of a variable tensor.<br>
2) add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.<br>

In [201]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [204]:
# Assign the final value a new value of 50
I.assign([0, 1, 2, 3, 50]).numpy() 

array([ 0,  1,  2,  3, 50])

In [205]:
# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10]).numpy()

array([10, 11, 12, 13, 60])

# Tensor and numpy

We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.<br>

Tensors can also be converted to NumPy arrays using:<br>

np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).<br>
tensor.numpy() - call on a tensor to convert to an ndarray.<br>

In [213]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3, 4, 5, 6, 7]))
J

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 4, 5, 6, 7])>

In [212]:
# Convert tensor J to NumPy with np.array()
J = np.array(J)
J, type(J)

(array([3, 4, 5, 6, 7]), numpy.ndarray)

In [214]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([3, 4, 5, 6, 7]), numpy.ndarray)

# Using @tf.function<br>
In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

In [219]:
# Create a simple function
def function(x, y):
    return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [220]:
y

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])>

In [221]:
function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [222]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
    return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

# Finding access to GPUs<br>
You can check if you've got access to a GPU using tf.config.list_physical_devices().

In [224]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [225]:
!nvidia-smi

Sat Oct 29 13:29:51 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.48       Driver Version: 517.48       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8     3W /  N/A |   4300MiB /  6144MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------